# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
neo_version=26.3.0.46-beta
mc_version=26.3
supported_minecraft_versions=26.3
